spring.application.name=all-arch-back-end
server.port=8080

jwt.secret=49110b68a516c0b84d3a145de47a3c1b0626cc2b400f707739c59e25e43668f69bfa041cfd867ee6a7e63a76b8e213a9ff45023e6f7d184ecce3c16dbe2dcd4a

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ALLARCH;encrypt=true;trustServerCertificate=true
spring.datasource.username=ALLARCHController
spring.datasource.password=ALLArch@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=allarch